name: Test GitHub Action

on:
  push:
    branches:
      - master

  workflow_dispatch:

      
jobs:
  docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'


      - name: Check Folder location
        run: |
          dir=$PWD
          python3 main.py --source $dir
