name: Test GitHub Action

on:
  push:
    branches:
      - master
      
jobs:
  docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Folder location
        run: |
        dir=$PWD
        python3 main.py --source dir
